name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10
        bundler-cache: true

    - name: Update Rubygems & Bundler
      run: |
        'gem update --system --no-document && gem update bundler --no-document'
        'gem install bundler -v "2.0.1" --force'

    - run: 'bundle install'

    - name: Test & report
      run: |
        bundle exec rake test

    - name: Codecov
      uses: codecov/codecov-action@v3
